### PR TITLE
Fixes #162

### LINKED ISSUE #162: VarUInt with value zero is encoded incorrectly
Bug is here:
https://github.com/hyperledger/quilt/blob/master/codec-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnUintCodec.java#L52

This needs to exclude the case where the value == 0

```java
if (bytes[0] == 0x00 && bytes.length > 1) {
```

### PR DESCRIPTION
**Pull request by sappenin**
* Only strip leading bytes if the byte-length is < 1
* Add unit test for AsnUintCodec

Signed-off-by: sappenin <sappenin@gmail.com>

### CODE REVIEW

File: codec-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnUintCodec.java [hunk 1]
```diff
@@ -38,18 +38,19 @@ public BigInteger decode() {
...
     byte[] bytes = value.toByteArray();
 
-    // BigInteger's toByteArray writes data in two's complement,
-    // so positive values may have a leading 0x00 byte.
-    if (bytes[0] == 0x00) {
+    // BigInteger's toByteArray writes data in two's complement, so positive values may have a
+    // leading 0x00 byte, which we want to strip off. However, we only want to strip these
+    // leading values off if the number of bytes is greater than 1 so that we don't produce an
+    // empty array when the BigInteger value is 0.
+    if (bytes[0] == 0x00 && bytes.length > 1) {
```
Comment (sublimator) [inline codec-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnUintCodec.java]: ooooh, ouch

File: codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+        {
+            BigInteger.valueOf(255L),
+            BaseEncoding.base16().decode("FF")
+        },
+        {
+            BigInteger.valueOf(1024L),
+            BaseEncoding.base16().decode("0400")
+        },
+        {
+            BigInteger.valueOf(16385L),
```
Comment (sublimator) [inline codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java]: Why not use hex literals ? 0x4001L etc ?

File: codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+  private final BigInteger expectedUint;
+  private final byte[] exptedEncodedBytes;
+
+  private AsnUintCodec codec;
+
+  /**
+   * Construct an instance of this parameterized test with the supplied inputs.
+   *
+   * @param expectedUint       The expected value, as a {@link BigInteger}, of {@code
+   *                           exptedEncodedBytes}, once encoded.
```
Comment (sublimator) [inline codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java]: > exptedEncodedBytes

typo

File: codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java (hunk 2 above)
Comment (sappenin) [reply codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java]: Good question - I think the test is clearer if we use Base10 numbers here because the purpose of this test is to ensure that a `BigInteger` will encode into binary. Since `BigInteger` is always operated upon in Base10, I want to be sure that the B10 number properly encodes/decodes. So, the `expectedUint` value is always represented in Base10 on purpose, and we only use the HEX value to construct the byte-array.

File: codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java (hunk 3 above)
Comment (sappenin) [reply codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java]: Fixed.

File: codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java (hunk 2 above)
Comment (sappenin) [reply codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java]: Actually, looking more closely at this test, @adrianhopebailie, this seems to be treating this like a Uint64, but instead the `AsnUintCodec` should be using a length-prefix, no? (since the number of octets can be arbitrary)

Comment (sublimator) [reply codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java]: I think the serializer classes handle that right ? (checking ... )

Comment (sublimator) [reply codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java]: Hrmmm, this codec doesn't actually seem to be registered at all for the OER rules?

Comment (sublimator) [reply codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java]: re: hex literals, I just thought they'd more easily eyeball match the hex encoding

Comment (sublimator) [reply codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java]: @sappenin 

Yeah, it seems I recalled correctly, and that the serializers handle all the length prefix encoding. 

See:
https://github.com/hyperledger/quilt/blob/b53a0511007c005c1f5455ec7f59639fb935e5b6/codec-framework/src/main/java/org/interledger/encoding/asn/framework/CodecContextFactory.java#L65
https://github.com/hyperledger/quilt/blob/b53a0511007c005c1f5455ec7f59639fb935e5b6/codec-framework/src/main/java/org/interledger/encoding/asn/serializers/oer/AsnOctetStringOerSerializer.java#L88

Comment (sappenin) [reply codec-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecTest.java]: Oh dang, you're totally right. I've been spending so much time in the Codecs I forgot about the Serializers.

Kk - I think this PR is good to go.
